version: '3.7'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8069 --reload
    env_file:
      - ./.env.dev
    volumes:
      - .:/code
    ports:
      - 8069:8069
    depends_on:
      - db
      - cache

  db:
    image: postgres:14-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  cache:
    image: redis:6.2-alpine
    volumes: 
      - cache:/data

volumes:
  postgres-data:
  cache: